In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [72]:
df = pd.read_csv("sentence_with_sentiment.csv")
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,Sentence1,Sentence2,Sentence3,Sentence4,Sentence5,Sentence6,Sentence7,Sentence8,Sentence9,Sentence10,...,Sentence22_sentiment,Sentence23_sentiment,Sentence24_sentiment,Sentence25_sentiment,Sentence26_sentiment,Sentence27_sentiment,Sentence28_sentiment,Sentence29_sentiment,Sentence30_sentiment,review_sentiment
0,I purchased the Trilogy with hoping my two cat...,The 3 yr old cat was fascinated for about 15 m...,The 5 year old watched for about a few minutes...,It is possible that because we have a wonderfu...,I will more than likely pass this on to a frie...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9100
1,There are usually one or more of my cats watch...,They seem to like the mice and birds the most ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0665
2,I bought the triliogy and have tested out all ...,It appears that volume 2 is the most well rece...,It's funny to watch my cat watch it bc she loo...,I turn this on sometimes when I'm leaving the ...,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8270
3,My female kitty could care less about these vi...,My little male however digs these.,"He doesn't go ape over them, but he really doe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7684
4,"If I had gotten just volume two, I would have ...","I read all the reviews, and knew that vol.","two was the best, hands down, but for few extr...",Since birds are a natural source of food for c...,two.,"Contrary to all the cartoons, cats are not fis...",Since gerbils and guinea pigs are not native w...,"Rodents are also a natural food, so volume one...","Also, the quality could have been better (for ...",NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9916

In [73]:
col = df.pop("review")
df.insert(0, col.name, col)

In [74]:
df.head()

,review,Sentence1,Sentence2,Sentence3,Sentence4,Sentence5,Sentence6,Sentence7,Sentence8,Sentence9,...,Sentence22_sentiment,Sentence23_sentiment,Sentence24_sentiment,Sentence25_sentiment,Sentence26_sentiment,Sentence27_sentiment,Sentence28_sentiment,Sentence29_sentiment,Sentence30_sentiment,review_sentiment
0,I purchased the Trilogy with hoping my two cat...,I purchased the Trilogy with hoping my two cat...,The 3 yr old cat was fascinated for about 15 m...,The 5 year old watched for about a few minutes...,It is possible that because we have a wonderfu...,I will more than likely pass this on to a frie...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9100
1,There are usually one or more of my cats watch...,There are usually one or more of my cats watch...,They seem to like the mice and birds the most ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0665
2,I bought the triliogy and have tested out all ...,I bought the triliogy and have tested out all ...,It appears that volume 2 is the most well rece...,It's funny to watch my cat watch it bc she loo...,I turn this on sometimes when I'm leaving the ...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8270
3,My female kitty could care less about these vi...,My female kitty could care less about these vi...,My little male however digs these.,"He doesn't go ape over them, but he really doe...",NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7684
4,"If I had gotten just volume two, I would have ...","If I had gotten just volume two, I would have ...","I read all the reviews, and knew that vol.","two was the best, hands down, but for few extr...",Since birds are a natural source of food for c...,two.,"Contrary to all the cartoons, cats are not fis...",Since gerbils and guinea pigs are not native w...,"Rodents are also a natural food, so volume one...","Also, the quality could have been better (for ...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9916

In [75]:
df['rating'] = original_df['overall']
df['help'] = original_df['helpful']
new_df = df.fillna('')

In [76]:
original_df = pd.read_csv("C:/Users/ZachXiong/Downloads/recategorized_dogs_cats_data.csv")
original_df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,related,...,categories,description,category_len,category_1,category_2,category_3,category_4,category_5,updated_category_4,final_category_4
0,A14CK12J7C7JRK,1223000893,Consumer in NorCal,"[0, 0]",I purchased the Trilogy with hoping my two cat...,3,Nice Distraction for my cats for about 15 minutes,1294790400,"01 12, 2011","{'also_bought': ['B000G1KNPK', 'B00BYHJ6UI', '...",...,"[['Pet Supplies', 'Cats', 'Toys']]",This combo pack provides you with all 3 Cat Si...,3,Pet Supplies,Cats,Toys,NaN,NaN,NaN,NaN
1,A39QHP5WLON5HV,1223000893,Melodee Placial,"[0, 0]",There are usually one or more of my cats watch...,5,Entertaining for my cats,1379116800,"09 14, 2013","{'also_bought': ['B000G1KNPK', 'B00BYHJ6UI', '...",...,"[['Pet Supplies', 'Cats', 'Toys']]",This combo pack provides you with all 3 Cat Si...,3,Pet Supplies,Cats,Toys,NaN,NaN,NaN,NaN
2,A2CR37UY3VR7BN,1223000893,Michelle Ashbery,"[0, 0]",I bought the triliogy and have tested out all ...,4,Entertaining,1355875200,"12 19, 2012","{'also_bought': ['B000G1KNPK', 'B00BYHJ6UI', '...",...,"[['Pet Supplies', 'Cats', 'Toys']]",This combo pack provides you with all 3 Cat Si...,3,Pet Supplies,Cats,Toys,NaN,NaN,NaN,NaN
3,A2A4COGL9VW2HY,1223000893,Michelle P,"[2, 2]",My female kitty could care less about these vi...,4,Happy to have them,1305158400,"05 12, 2011","{'also_bought': ['B000G1KNPK', 'B00BYHJ6UI', '...",...,"[['Pet Supplies', 'Cats', 'Toys']]",This combo pack provides you with all 3 Cat Si...,3,Pet Supplies,Cats,Toys,NaN,NaN,NaN,NaN
4,A2UBQA85NIGLHA,1223000893,"Tim Isenhour ""Timbo""","[6, 7]","If I had gotten just volume two, I would have ...",3,You really only need vol 2,1330905600,"03 5, 2012","{'also_bought': ['B000G1KNPK', 'B00BYHJ6UI', '...",...,"[['Pet Supplies', 'Cats', 'Toys']]",This combo pack provides you with all 3 Cat Si...,3,Pet Supplies,Cats,Toys,NaN,NaN,NaN,NaN

In [78]:
df.columns

Index(['review', 'Sentence1', 'Sentence2', 'Sentence3', 'Sentence4',
       'Sentence5', 'Sentence6', 'Sentence7', 'Sentence8', 'Sentence9',
       'Sentence10', 'Sentence11', 'Sentence12', 'Sentence13', 'Sentence14',
       'Sentence15', 'Sentence16', 'Sentence17', 'Sentence18', 'Sentence19',
       'Sentence20', 'Sentence21', 'Sentence22', 'Sentence23', 'Sentence24',
       'Sentence25', 'Sentence26', 'Sentence27', 'Sentence28', 'Sentence29',
       'Sentence30', 'Sentence1_sentiment', 'Sentence2_sentiment',
       'Sentence3_sentiment', 'Sentence4_sentiment', 'Sentence5_sentiment',
       'Sentence6_sentiment', 'Sentence7_sentiment', 'Sentence8_sentiment',
       'Sentence9_sentiment', 'Sentence10_sentiment', 'Sentence11_sentiment',
       'Sentence12_sentiment', 'Sentence13_sentiment', 'Sentence14_sentiment',
       'Sentence15_sentiment', 'Sentence16_sentiment', 'Sentence17_sentiment',
       'Sentence18_sentiment', 'Sentence19_sentiment', 'Sentence20_sentiment',
       'Sentence21_sentiment', 'Sentence22_sentiment', 'Sentence23_sentiment',
       'Sentence24_sentiment', 'Sentence25_sentiment', 'Sentence26_sentiment',
       'Sentence27_sentiment', 'Sentence28_sentiment', 'Sentence29_sentiment',
       'Sentence30_sentiment', 'review_sentiment', 'rating', 'help'],
      dtype='object')

In [79]:
avg_sentiment = []
for i, item in new_df.iterrows():
    if item['Sentence1'] == '':
        avg_sentiment.append(0)
        continue
    flag = 0
    for col_num in range(1, 31):
        if item[new_df.columns.tolist()[col_num]]== '' or col_num == 30:
            flag = col_num
            break
    avg_sentiment.append(sum(list(item[df.columns.tolist()[31:31+flag]])) / flag)

In [82]:
len(avg_sentiment), new_df.shape

(129904, (129904, 65))

In [83]:
new_df['avg_sentiment'] = avg_sentiment

In [84]:
new_df.head()

,review,Sentence1,Sentence2,Sentence3,Sentence4,Sentence5,Sentence6,Sentence7,Sentence8,Sentence9,...,Sentence25_sentiment,Sentence26_sentiment,Sentence27_sentiment,Sentence28_sentiment,Sentence29_sentiment,Sentence30_sentiment,review_sentiment,rating,help,avg_sentiment
0,I purchased the Trilogy with hoping my two cat...,I purchased the Trilogy with hoping my two cat...,The 3 yr old cat was fascinated for about 15 m...,The 5 year old watched for about a few minutes...,It is possible that because we have a wonderfu...,I will more than likely pass this on to a frie...,,,,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.9100,3,"[0, 0]",0.263867
1,There are usually one or more of my cats watch...,There are usually one or more of my cats watch...,They seem to like the mice and birds the most ...,,,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0665,5,"[0, 0]",-0.020933
2,I bought the triliogy and have tested out all ...,I bought the triliogy and have tested out all ...,It appears that volume 2 is the most well rece...,It's funny to watch my cat watch it bc she loo...,I turn this on sometimes when I'm leaving the ...,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.8270,4,"[0, 0]",0.337480
3,My female kitty could care less about these vi...,My female kitty could care less about these vi...,My little male however digs these.,"He doesn't go ape over them, but he really doe...",,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.7684,4,"[2, 2]",0.321250
4,"If I had gotten just volume two, I would have ...","If I had gotten just volume two, I would have ...","I read all the reviews, and knew that vol.","two was the best, hands down, but for few extr...",Since birds are a natural source of food for c...,two.,"Contrary to all the cartoons, cats are not fis...",Since gerbils and guinea pigs are not native w...,"Rodents are also a natural food, so volume one...","Also, the quality could have been better (for ...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.9916,3,"[6, 7]",0.314240

In [85]:
# scale the sentiment score to 1,5 range
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(1,5))
a = scaler.fit_transform(new_df[['avg_sentiment']])
new_df['avg_sentiment_scaled'] = a

In [86]:
new_df.head()

,review,Sentence1,Sentence2,Sentence3,Sentence4,Sentence5,Sentence6,Sentence7,Sentence8,Sentence9,...,Sentence26_sentiment,Sentence27_sentiment,Sentence28_sentiment,Sentence29_sentiment,Sentence30_sentiment,review_sentiment,rating,help,avg_sentiment,avg_sentiment_scaled
0,I purchased the Trilogy with hoping my two cat...,I purchased the Trilogy with hoping my two cat...,The 3 yr old cat was fascinated for about 15 m...,The 5 year old watched for about a few minutes...,It is possible that because we have a wonderfu...,I will more than likely pass this on to a frie...,,,,,...,0.0,0.0,0.0,0.0,0.0,0.9100,3,"[0, 0]",0.263867,3.716547
1,There are usually one or more of my cats watch...,There are usually one or more of my cats watch...,They seem to like the mice and birds the most ...,,,,,,,,...,0.0,0.0,0.0,0.0,0.0,-0.0665,5,"[0, 0]",-0.020933,2.874504
2,I bought the triliogy and have tested out all ...,I bought the triliogy and have tested out all ...,It appears that volume 2 is the most well rece...,It's funny to watch my cat watch it bc she loo...,I turn this on sometimes when I'm leaving the ...,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.8270,4,"[0, 0]",0.337480,3.934193
3,My female kitty could care less about these vi...,My female kitty could care less about these vi...,My little male however digs these.,"He doesn't go ape over them, but he really doe...",,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.7684,4,"[2, 2]",0.321250,3.886207
4,"If I had gotten just volume two, I would have ...","If I had gotten just volume two, I would have ...","I read all the reviews, and knew that vol.","two was the best, hands down, but for few extr...",Since birds are a natural source of food for c...,two.,"Contrary to all the cartoons, cats are not fis...",Since gerbils and guinea pigs are not native w...,"Rodents are also a natural food, so volume one...","Also, the quality could have been better (for ...",...,0.0,0.0,0.0,0.0,0.0,0.9916,3,"[6, 7]",0.314240,3.865482

In [87]:
# calculate the helpness (# helpful / # of total)
new_df['help'] = new_df['help'].apply(lambda x: int(x.split(',')[0][1:]) / int(x.split(',')[1][:-1]) if int(x.split(',')[1][:-1]) != 0  else 0)

In [88]:
new_df.head()

,review,Sentence1,Sentence2,Sentence3,Sentence4,Sentence5,Sentence6,Sentence7,Sentence8,Sentence9,...,Sentence26_sentiment,Sentence27_sentiment,Sentence28_sentiment,Sentence29_sentiment,Sentence30_sentiment,review_sentiment,rating,help,avg_sentiment,avg_sentiment_scaled
0,I purchased the Trilogy with hoping my two cat...,I purchased the Trilogy with hoping my two cat...,The 3 yr old cat was fascinated for about 15 m...,The 5 year old watched for about a few minutes...,It is possible that because we have a wonderfu...,I will more than likely pass this on to a frie...,,,,,...,0.0,0.0,0.0,0.0,0.0,0.9100,3,0.000000,0.263867,3.716547
1,There are usually one or more of my cats watch...,There are usually one or more of my cats watch...,They seem to like the mice and birds the most ...,,,,,,,,...,0.0,0.0,0.0,0.0,0.0,-0.0665,5,0.000000,-0.020933,2.874504
2,I bought the triliogy and have tested out all ...,I bought the triliogy and have tested out all ...,It appears that volume 2 is the most well rece...,It's funny to watch my cat watch it bc she loo...,I turn this on sometimes when I'm leaving the ...,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.8270,4,0.000000,0.337480,3.934193
3,My female kitty could care less about these vi...,My female kitty could care less about these vi...,My little male however digs these.,"He doesn't go ape over them, but he really doe...",,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.7684,4,1.000000,0.321250,3.886207
4,"If I had gotten just volume two, I would have ...","If I had gotten just volume two, I would have ...","I read all the reviews, and knew that vol.","two was the best, hands down, but for few extr...",Since birds are a natural source of food for c...,two.,"Contrary to all the cartoons, cats are not fis...",Since gerbils and guinea pigs are not native w...,"Rodents are also a natural food, so volume one...","Also, the quality could have been better (for ...",...,0.0,0.0,0.0,0.0,0.0,0.9916,3,0.857143,0.314240,3.865482